# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.5
  TargetRailsVersion: 8.0
  DisplayCopNames: true

Rails:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
